name: CI - Train & Save Artifact

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write # agar bisa push

jobs:
  train-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install mlflow pandas scikit-learn matplotlib seaborn

      - name: Run training (MLflow Project)
        run: |
          cd MLProject
          mlflow run . --no-conda --experiment-name=ci-experiment

      - name: Commit model artifact
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add MLProject/model MLProject/mlruns || true
          git commit -m "Auto-update trained model [CI]" || echo "No changes"
          git push
